"""add supervisor assignment

Revision ID: 4cd49d9f35a4
Revises: db6068ad4187
Create Date: 2025-12-20 01:50:50.831981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd49d9f35a4'
down_revision: Union[str, Sequence[str], None] = 'db6068ad4187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisorassignment',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('preventionist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preventionist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('supervisor_id')
    )
    with op.batch_alter_table('supervisorassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervisorassignment_preventionist_id'), ['preventionist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisorassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervisorassignment_preventionist_id'))

    op.drop_table('supervisorassignment')
    # ### end Alembic commands ###
