"""add admin role

Revision ID: 5dc108620b75
Revises: dff8a3b53cc9
Create Date: 2025-12-20 13:29:33.350274

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '5dc108620b75'
down_revision: Union[str, Sequence[str], None] = 'dff8a3b53cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
