"""make activity assignment mandatory

Revision ID: 8cd03ace122e
Revises: faca364dd39f
Create Date: 2025-12-20 08:37:03.303167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd03ace122e'
down_revision: Union[str, Sequence[str], None] = 'faca364dd39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
