"""add admin role

Revision ID: db6068ad4187
Revises: 620e2fe4367e
Create Date: 2025-12-20 00:38:12.147065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6068ad4187'
down_revision: Union[str, Sequence[str], None] = '620e2fe4367e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('scheduled_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('scheduled_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
