"""replace is_done with status enum in todoitem

Revision ID: dff8a3b53cc9
Revises: 35e131c3fb24
Create Date: 2025-12-20 13:15:24.106637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dff8a3b53cc9'
down_revision: Union[str, Sequence[str], None] = '35e131c3fb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('todoitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'yes', 'no', 'not_apply', name='todostatus'), nullable=True))
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=11), nullable=True))

    # ### end Alembic commands ###
