"""resolve ambiguous foreign keys in supervisorassignment

Revision ID: e0dc32bf10ec
Revises: 2ea209215272
Create Date: 2025-12-20 03:37:02.973865

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e0dc32bf10ec'
down_revision: Union[str, Sequence[str], None] = '2ea209215272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisorassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervisorassignment_preventionist_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisorassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervisorassignment_preventionist_id'), ['preventionist_id'], unique=False)

    # ### end Alembic commands ###
