"""link activity to activitytemplate

Revision ID: faca364dd39f
Revises: e0dc32bf10ec
Create Date: 2025-12-20 05:05:42.848641

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'faca364dd39f'
down_revision: Union[str, Sequence[str], None] = 'e0dc32bf10ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
